services:
  firefox:
    image: seleniarm/node-firefox:4.20
    shm_size: "2g"
    deploy:
      replicas: 2
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  vendor-portal:
    image: nikitosnegritos/selenium
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - TEST_SUITE=vendor-portal.xml
      - THREAD_COUNT=2
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: nikitosnegritos/selenium
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - TEST_SUITE=flight-reservation.xml
      - THREAD_COUNT=4
    volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output
